In [1]:
import nflreadpy as nfl
import polars as pl
import sys
from pathlib import Path
import os
import plotly.express as px
import plotly.graph_objects as go
from scipy import interpolate

In [2]:
PROJECT_ROOT = Path(os.getcwd()).resolve().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.annual_av_analysis import (
    aggregate_player_av,
    logarithmic_av_fit,
    logarithmic_fit_result_to_dataframe,
    prepare_av_data,
    exponential_av_fit,
    fit_result_to_dataframe,
)
from src.data_ingest import load_parquets_from_dir

RAW_DIR = PROJECT_ROOT / "data/raw/stathead/annual_av"
PROCESSED_DIR = PROJECT_ROOT / "data/processed"
FIGURES_DIR = PROJECT_ROOT / "outputs/figures"
_TRADE_COLORS = ["#e15759", "#f28e2b", "#76b7b2", "#59a14f", "#b07aa1"]

In [21]:
PFF_WAR = pl.read_csv(PROCESSED_DIR / "pff_war_draft_chart.csv", infer_schema_length=None)
f = interpolate.interp1d(PFF_WAR["Pick"], PFF_WAR["PFF_WAR_Normalized"])
Pick = list(range(1,225))
PFF_WAR_Normalized = f(Pick)

In [25]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=Pick,
    y=PFF_WAR_Normalized,
    mode="lines",
))

fig.update_layout(
        title="Pick Value Comparison — Normalized to Pick 1",
        xaxis=dict(title="Overall Pick", range=[1, 225]),
        yaxis=dict(title="Normalized Value (Pick 1 = 1.0)"),
        template="plotly_white",
        legend=dict(groupclick="toggleitem"),
    )

fig.show()

In [27]:
df = pl.DataFrame({
    "Pick":Pick,
    "PFF_WAR_Normalized":PFF_WAR_Normalized
    })
df.write_csv("pff_war_draft_chart.csv")

In [4]:
player_av_lf = aggregate_player_av(prepare_av_data(load_parquets_from_dir(RAW_DIR)))
exp_fit_results = exponential_av_fit(player_av_lf, max_pick=250)
log_fit_results = logarithmic_av_fit(player_av_lf,max_pick=250)

In [12]:
print(player_av_lf.lazy()
        .filter(pl.col("Pick") <= 250)
        .drop_nulls()
        .collect()
        .sort("Pick").describe())
print(exp_fit_results['infodict'])

shape: (9, 6)
┌────────────┬───────────────┬────────────┬─────────────┬────────────┬────────────────────┐
│ statistic  ┆ Player        ┆ Pick       ┆ Draft Year  ┆ Draft Team ┆ rookie_contract_av │
│ ---        ┆ ---           ┆ ---        ┆ ---         ┆ ---        ┆ ---                │
│ str        ┆ str           ┆ f64        ┆ f64         ┆ str        ┆ f64                │
╞════════════╪═══════════════╪════════════╪═════════════╪════════════╪════════════════════╡
│ count      ┆ 11582         ┆ 11582.0    ┆ 11582.0     ┆ 11582      ┆ 11582.0            │
│ null_count ┆ 0             ┆ 0.0        ┆ 0.0         ┆ 0          ┆ 0.0                │
│ mean       ┆ null          ┆ 113.362373 ┆ 1998.515541 ┆ null       ┆ 10.78104           │
│ std        ┆ null          ┆ 70.515336  ┆ 15.66787    ┆ null       ┆ 10.929809          │
│ min        ┆ 'Omar Ellison ┆ 1.0        ┆ 1970.0      ┆ ARI        ┆ 0.0                │
│ 25%        ┆ null          ┆ 52.0       ┆ 1985.0      ┆ null       ┆ 2.0                │
│ 50%        ┆ null          ┆ 108.0      ┆ 1999.0      ┆ null       ┆ 7.0                │
│ 75%        ┆ null          ┆ 171.0      ┆ 2012.0      ┆ null       ┆ 17.0               │
│ max        ┆ Zyon McCollum ┆ 250.0      ┆ 2024.0      ┆ WAS        ┆ 71.0               │
└────────────┴───────────────┴────────────┴─────────────┴────────────┴────────────────────┘
{'fvec': array([-1.36335377, 25.63664623, 19.63664623, ..., -7.90723107,
        5.09276893,  4.09276893], shape=(11582,)), 'nfev': 21, 'fjac': array([[ 3.68755118e+04,  5.93794373e-04,  5.93794373e-04, ...,
         2.39198874e-03,  2.39198874e-03,  2.39198874e-03],
       [-9.87095505e+01, -4.28768534e+01,  2.19425655e-02, ...,
         1.77633700e-02,  1.77633700e-02,  1.77633700e-02],
       [-2.90188163e+01, -6.49661478e+00, -2.78279704e+01, ...,
        -6.66901213e-03, -6.66901213e-03, -6.66901213e-03]],
      shape=(3, 11582)), 'ipvt': array([1, 2, 0], dtype=int32), 'qtf': array([-0.00738764,  0.01631278,  0.00375717])}

In [3]:
trade_charts = {
    "Jimmy Johnson": (
        pl.read_csv(PROCESSED_DIR / "jimmy_johnson_trade_chart.csv", infer_schema_length=None)
        .unique(subset=["Pick"], keep="first")
        .sort("Pick")
        .select(["Pick", "Value"])
        .with_columns(pl.col("Pick").cast(pl.Int64))
    ),
    "Fitzgerald-Spielberger": (
        pl.read_csv(PROCESSED_DIR / "fitzgerald_spielberger_trade_chart.csv", infer_schema_length=None)
        .select(["Pick", "Value"])
        .with_columns(pl.col("Pick").cast(pl.Int64))
    ),
    "PFF WAR": (
        pl.read_csv(PROCESSED_DIR / "pff_war_draft_chart.csv", infer_schema_length=None)
        .rename({"PFF_WAR_Normalized": "Value"})
        .select(["Pick", "Value"])
        .with_columns(pl.col("Pick").cast(pl.Int64))
    ),
    "5-Year AV": (
        pl.read_csv(PROCESSED_DIR / "5_year_av_chart.csv", infer_schema_length=None)
        .rename({"Pk": "Pick", "FP Val": "Value"})
        .select(["Pick", "Value"])
        .with_columns(pl.col("Pick").cast(pl.Int64))
    ),
    "Rich Hill": (
        pl.read_csv(PROCESSED_DIR / "Rich-Hill.csv", infer_schema_length=None)
        .rename({"pick": "Pick", "value": "Value"})
        .select(["Pick", "Value"])
        .with_columns(pl.col("Pick").cast(pl.Int64))
    ),
}

In [4]:
fig = go.Figure()

for i, (label, df) in enumerate(trade_charts.items()):
        print(label)
        color = _TRADE_COLORS[i % len(_TRADE_COLORS)]
        val_at_1 = df.filter(pl.col("Pick") == 1)["Value"][0]
        chart_df = df.filter(pl.col("Pick") <= 250)
        x = chart_df["Pick"].to_list()
        y_norm = [v / val_at_1 for v in chart_df["Value"].to_list()]

        fig.add_trace(go.Scatter(
            x=x,
            y=y_norm,
            mode="lines",
            line=dict(color=color, width=2, dash="dash"),
            name=label,
            legendgroup="trade_charts",
            legendgrouptitle=dict(text="Trade Charts") if i == 0 else {},
        ))

fig.update_layout(
        title="Pick Value Comparison — Normalized to Pick 1",
        xaxis=dict(title="Overall Pick", range=[1, 250]),
        yaxis=dict(title="Normalized Value (Pick 1 = 1.0)"),
        template="plotly_white",
        legend=dict(groupclick="toggleitem"),
    )

fig.show()

Jimmy Johnson
Fitzgerald-Spielberger
PFF WAR
5-Year AV
Rich Hill

In [7]:
from src.annual_av_analysis import lookup_player_av, aggregate_player_av, prepare_av_data
from src.data_ingest import load_parquets_from_dir
from pathlib import Path

RAW_DIR = Path('../data/raw/stathead/annual_av')
lf = aggregate_player_av(prepare_av_data(load_parquets_from_dir(RAW_DIR)), max_seasons_from_draft=5)
result = lookup_player_av('Peyton Manning', lf)
print(result)

shape: (1, 5)
┌────────────────┬────────────┬──────┬────────────┬────────────────────┐
│ Player         ┆ Draft Year ┆ Pick ┆ Draft Team ┆ rookie_contract_av │
│ ---            ┆ ---        ┆ ---  ┆ ---        ┆ ---                │
│ str            ┆ i64        ┆ i64  ┆ str        ┆ f64                │
╞════════════════╪════════════╪══════╪════════════╪════════════════════╡
│ Peyton Manning ┆ 1998       ┆ 1    ┆ IND        ┆ 76.0               │
└────────────────┴────────────┴──────┴────────────┴────────────────────┘

In [2]:
# Load current season play-by-play data
pbp = nfl.load_pbp()

# Load player game-level stats for multiple seasons
player_stats = nfl.load_player_stats([2022, 2023])

In [6]:
pfr_advanced = nfl.load_pfr_advstats([2022, 2023])

In [7]:
pfr_advanced.columns

['game_id',
 'pfr_game_id',
 'season',
 'week',
 'game_type',
 'team',
 'opponent',
 'pfr_player_name',
 'pfr_player_id',
 'passing_drops',
 'passing_drop_pct',
 'receiving_drop',
 'receiving_drop_pct',
 'passing_bad_throws',
 'passing_bad_throw_pct',
 'times_sacked',
 'times_blitzed',
 'times_hurried',
 'times_hit',
 'times_pressured',
 'times_pressured_pct',
 'def_times_blitzed',
 'def_times_hurried',
 'def_times_hitqb']

In [3]:
trades = nfl.load_trades()

In [5]:
trades.filter(pl.col('gave')=="DET").filter(pl.col('season')==2025)

shape: (8, 11)
┌──────────┬────────┬────────────┬──────┬───┬─────────────┬─────────────┬──────────┬───────────────┐
│ trade_id ┆ season ┆ trade_date ┆ gave ┆ … ┆ pick_number ┆ conditional ┆ pfr_id   ┆ pfr_name      │
│ ---      ┆ ---    ┆ ---        ┆ ---  ┆   ┆ ---         ┆ ---         ┆ ---      ┆ ---           │
│ f64      ┆ i32    ┆ date       ┆ str  ┆   ┆ f64         ┆ f64         ┆ str      ┆ str           │
╞══════════╪════════╪════════════╪══════╪═══╪═════════════╪═════════════╪══════════╪═══════════════╡
│ 1928.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ 60.0        ┆ 0.0         ┆ HarvRJ00 ┆ RJ Harvey     │
│ 1928.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ 130.0       ┆ 0.0         ┆ MoorMa04 ┆ Malachi Moore │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ 102.0       ┆ 0.0         ┆ FeltTa00 ┆ Tai Felton    │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ null        ┆ 0.0         ┆ null     ┆ null          │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ null        ┆ 0.0         ┆ null     ┆ null          │
│ 1948.0   ┆ 2025   ┆ 2025-04-26 ┆ DET  ┆ … ┆ 182.0       ┆ 0.0         ┆ BorrAn00 ┆ Andres        │
│          ┆        ┆            ┆      ┆   ┆             ┆             ┆          ┆ Borregales    │
│ 1948.0   ┆ 2025   ┆ 2025-04-26 ┆ DET  ┆ … ┆ 228.0       ┆ 0.0         ┆ SmitBr09 ┆ Brashard      │
│          ┆        ┆            ┆      ┆   ┆             ┆             ┆          ┆ Smith         │
│ 1974.0   ┆ 2025   ┆ 2025-08-27 ┆ DET  ┆ … ┆ null        ┆ null        ┆ PatrTi00 ┆ Tim Patrick   │
└──────────┴────────┴────────────┴──────┴───┴─────────────┴─────────────┴──────────┴───────────────┘

In [8]:
trades.filter(pl.col('gave')=="JAX").filter(pl.col('season')==2025)

shape: (13, 11)
┌──────────┬────────┬────────────┬──────┬───┬─────────────┬─────────────┬──────────┬───────────────┐
│ trade_id ┆ season ┆ trade_date ┆ gave ┆ … ┆ pick_number ┆ conditional ┆ pfr_id   ┆ pfr_name      │
│ ---      ┆ ---    ┆ ---        ┆ ---  ┆   ┆ ---         ┆ ---         ┆ ---      ┆ ---           │
│ f64      ┆ i32    ┆ date       ┆ str  ┆   ┆ f64         ┆ f64         ┆ str      ┆ str           │
╞══════════╪════════╪════════════╪══════╪═══╪═════════════╪═════════════╪══════════╪═══════════════╡
│ 1909.0   ┆ 2025   ┆ 2025-03-06 ┆ JAX  ┆ … ┆ null        ┆ null        ┆ KirkCh01 ┆ Christian     │
│          ┆        ┆            ┆      ┆   ┆             ┆             ┆          ┆ Kirk          │
│ 1919.0   ┆ 2025   ┆ 2025-04-24 ┆ JAX  ┆ … ┆ 5.0         ┆ 0.0         ┆ GrahMa00 ┆ Mason Graham  │
│ 1919.0   ┆ 2025   ┆ 2025-04-24 ┆ JAX  ┆ … ┆ 36.0        ┆ 0.0         ┆ JudkQu00 ┆ Quinshon      │
│          ┆        ┆            ┆      ┆   ┆             ┆             ┆          ┆ Judkins       │
│ 1919.0   ┆ 2025   ┆ 2025-04-24 ┆ JAX  ┆ … ┆ 126.0       ┆ 0.0         ┆ SampDy00 ┆ Dylan Sampson │
│ 1919.0   ┆ 2025   ┆ 2025-04-24 ┆ JAX  ┆ … ┆ null        ┆ 0.0         ┆ null     ┆ null          │
│ …        ┆ …      ┆ …          ┆ …    ┆ … ┆ …           ┆ …           ┆ …        ┆ …             │
│ 1932.0   ┆ 2025   ┆ 2025-04-25 ┆ JAX  ┆ … ┆ 102.0       ┆ 0.0         ┆ FeltTa00 ┆ Tai Felton    │
│ 1932.0   ┆ 2025   ┆ 2025-04-25 ┆ JAX  ┆ … ┆ 142.0       ┆ 0.0         ┆ MillRy02 ┆ Rylie Mills   │
│ 1959.0   ┆ 2025   ┆ 2025-08-17 ┆ JAX  ┆ … ┆ null        ┆ null        ┆ FortLu01 ┆ Luke Fortner  │
│ 1967.0   ┆ 2025   ┆ 2025-08-24 ┆ JAX  ┆ … ┆ null        ┆ null        ┆ JohnFr01 ┆ Fred Johnson  │
│ 1974.0   ┆ 2025   ┆ 2025-08-27 ┆ JAX  ┆ … ┆ null        ┆ 0.0         ┆ null     ┆ null          │
└──────────┴────────┴────────────┴──────┴───┴─────────────┴─────────────┴──────────┴───────────────┘

In [8]:
trades.filter(pl.col('trade_id')==1929)

shape: (6, 11)
┌──────────┬────────┬────────────┬──────┬───┬─────────────┬─────────────┬──────────┬───────────────┐
│ trade_id ┆ season ┆ trade_date ┆ gave ┆ … ┆ pick_number ┆ conditional ┆ pfr_id   ┆ pfr_name      │
│ ---      ┆ ---    ┆ ---        ┆ ---  ┆   ┆ ---         ┆ ---         ┆ ---      ┆ ---           │
│ f64      ┆ i32    ┆ date       ┆ str  ┆   ┆ f64         ┆ f64         ┆ str      ┆ str           │
╞══════════╪════════╪════════════╪══════╪═══╪═════════════╪═════════════╪══════════╪═══════════════╡
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ JAX  ┆ … ┆ 70.0        ┆ 0.0         ┆ TeSlIs00 ┆ Isaac TeSlaa  │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ JAX  ┆ … ┆ 182.0       ┆ 0.0         ┆ BorrAn00 ┆ Andres        │
│          ┆        ┆            ┆      ┆   ┆             ┆             ┆          ┆ Borregales    │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ JAX  ┆ … ┆ null        ┆ 0.0         ┆ null     ┆ null          │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ 102.0       ┆ 0.0         ┆ FeltTa00 ┆ Tai Felton    │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ null        ┆ 0.0         ┆ null     ┆ null          │
│ 1929.0   ┆ 2025   ┆ 2025-04-25 ┆ DET  ┆ … ┆ null        ┆ 0.0         ┆ null     ┆ null          │
└──────────┴────────┴────────────┴──────┴───┴─────────────┴─────────────┴──────────┴───────────────┘